### ISSUE TITLE
opencv2.4

### ISSUE THREAD

**Issue by ZhengyiLuo** [ExSidius/openpose-docker#2]
Thanks a ton for the amazing setup!

Wondering how is opencv2.4 installed, when the image does not contain any setup for it? Am also trying to setup opencv2.4 but facing cuda issues.

**Comment by ExSidius** [comment]
`opencv-python` should have that built into a wheel. What specifically are you trying to do/running into?

**Comment by ZhengyiLuo** [comment]
opencv-python will install the 3.2 version. It turns out 2.4 is shipped together with ubuntu 16.04 and I am trying to get this to work on 18.04. Resolved after using a different base image.
